# Generated by Django 5.2.1 on 2025-06-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.AddField(
            model_name='service',
            name='whats_included',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('profesional_photography', 'Photography'), ('videography', 'Videography'), ('ai_powered_editing', 'AI Powered Editing'), ('custom_tshirt_printing', 'Cutome T-Shirt Printing'), ('drone_footage', 'Drone Footage'), ('e_commerce_photography', 'E-Commerce Photography'), ('id_card_making', 'ID Card Making'), ('tshirt_printing', 'T-Shirt Printing'), ('albumb_designing', 'Album Designing'), ('photo_framing', 'Photo Framing'), ('ai_assistant', 'AI Assistant Development')], max_length=50),
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.service')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
