# Generated by Django 5.2.1 on 2025-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_uploadedmedia_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='whats_included',
            field=models.TextField(help_text='Enter one item per line'),
        ),
    ]
